bucket: 'zooniverse-static'
bucket_path: 'talk.diskdetective.org'
external_scripts: [
  "//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js",
  "//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.0/backbone-min.js"
]
