# To generate a proper key, do something like this:
#  keys = ('a'..'z').to_a + ('A'..'Z').to_a + ('0'..'9').to_a
#  token = ""
#  128.times{ token += keys[rand(keys.length)] }

token: hsRgH7dFQ1gCpI6tT5iAWEkIfFpJAIXmR35WhP9WbD5bA3xcwjWB01rZUukrWDget0g2lrD1T6Aee6ZK59R0DK8hav7LdpD53PsiJ0N67vp95hYGMKaBDPp8ChBYVQiD
